export const appliedPageData = [
    {
        id : 1,
        name : 'Harsh Bisht',
        email : 'harshbisht@gmail.com',
        field2 : '2000321540026',
        field3 : 'CSDS A',
        field4 : 'ACCENTURE',
        field5 : 'SERVICE',
        field6 : '400000',
        field7 : 'APPLIED',
    },
    {
        id : 2,
        name : 'Harsh Bisht',
        email : 'harshbisht@gmail.com',
        field2 : '2000321540026',
        field3 : 'CSDS A',
        field4 : 'ACCENTURE',
        field5 : 'SERVICE',
        field6 : '400000',
        field7 : 'APPLIED',
    },
    {
        id : 3,
        name : 'Harsh Bisht',
        email : 'harshbisht@gmail.com',
        field2 : '2000321540026',
        field3 : 'CSDS A',
        field4 : 'ACCENTURE',
        field5 : 'SERVICE',
        field6 : '400000',
        field7 : 'APPLIED',
    },
    {
        id : 4,
        name : 'Harsh Bisht',
        email : 'harshbisht@gmail.com',
        field2 : '2000321540026',
        field3 : 'CSDS A',
        field4 : 'ACCENTURE',
        field5 : 'SERVICE',
        field6 : '400000',
        field7 : 'APPLIED',
    },
    {
        id : 5,
        name : 'Harsh Bisht',
        email : 'harshbisht@gmail.com',
        field2 : '2000321540026',
        field3 : 'CSDS A',
        field4 : 'ACCENTURE',
        field5 : 'SERVICE',
        field6 : '400000',
        field7 : 'APPLIED',
    },
    {
        id : 6,
        name : 'Harsh Bisht',
        email : 'harshbisht@gmail.com',
        field2 : '2000321540026',
        field3 : 'CSDS A',
        field4 : 'ACCENTURE',
        field5 : 'SERVICE',
        field6 : '400000',
        field7 : 'APPLIED',
    },
    {
        id : 7,
        name : 'Harsh Bisht',
        email : 'harshbisht@gmail.com',
        field2 : '2000321540026',
        field3 : 'CSDS A',
        field4 : 'ACCENTURE',
        field5 : 'SERVICE',
        field6 : '400000',
        field7 : 'APPLIED',
    },
]