export const companyListData = [
    {
        id : 1,
        type : 'COMPANY',
        nameField : 'Amazon',
        field2 : 'Product',
        field3 : '26 June 2024',
        field4 : '4000000',
        field5 : '2024',
        field6 : 'i',
    },
    {
        id : 2,
        type : 'COMPANY',
        nameField : 'Accenture',
        field2 : 'Product',
        field3 : '26 June 2024',
        field4 : '4000000',
        field5 : '2024',
        field6 : 'i',
    },
    {
        id : 3,
        type : 'COMPANY',
        nameField : 'Microsoft',
        field2 : 'Product',
        field3 : '26 June 2024',
        field4 : '4000000',
        field5 : '2024',
        field6 : 'i',
    },
    {
        id : 4,
        type : 'COMPANY',
        nameField : 'EXC',
        field2 : 'Product',
        field3 : '26 June 2024',
        field4 : '4000000',
        field5 : '2024',
        field6 : 'i',
    },
]