export const placedCardData = [
    {
        id : 1, 
        companyName:"TCS",
        companyType:"Service",
        companyCTC:"400000",
        status:"Placed",
        buttonColor:"lightGreen",
    },
    {
        id : 2, 
        companyName:"TCS",
        companyType:"Service",
        companyCTC:"400000",
        status:"Placed",
        buttonColor:"lightGreen",
    },
    {
        id : 3, 
        companyName:"TCS",
        companyType:"Service",
        companyCTC:"400000",
        status:"Placed",
        buttonColor:"lightGreen",
    },
    {
        id : 4, 
        companyName:"TCS",
        companyType:"Service",
        companyCTC:"400000",
        status:"Placed",
        buttonColor:"lightGreen",
    },
    {
        id : 5, 
        companyName:"TCS",
        companyType:"Service",
        companyCTC:"400000",
        status:"Placed",
        buttonColor:"lightGreen",
    },
    {
        id : 6, 
        companyName:"TCS",
        companyType:"Service",
        companyCTC:"400000",
        status:"Placed",
        buttonColor:"lightGreen",
    },
]