export const placedPageData = [
    {
        id : 1, 
        type : 'PLACED',
        nameField : 'Amazon',
        field2 : '2',
        field3 : '400000',
        field6 : 'i',
    },
    {
        id : 2, 
        type : 'PLACED',
        nameField : 'Amazon',
        field2 : '2',
        field3 : '400000',
        field6 : 'i',
    },
    {
        id : 3, 
        type : 'PLACED',
        nameField : 'Amazon',
        field2 : '2',
        field3 : '400000',
        field6 : 'i',
    },
    {
        id : 4, 
        type : 'PLACED',
        nameField : 'Amazon',
        field2 : '2',
        field3 : '400000',
        field6 : 'i',
    },
    {
        id : 5, 
        type : 'PLACED',
        nameField : 'Amazon',
        field2 : '2',
        field3 : '400000',
        field6 : 'i',
    },
    {
        id : 6, 
        type : 'PLACED',
        nameField : 'Amazon',
        field2 : '2',
        field3 : '400000',
        field6 : 'i',
    },
    {
        id : 7, 
        type : 'PLACED',
        nameField : 'Amazon',
        field2 : '2',
        field3 : '400000',
        field6 : 'i',
    },
]