export const studentData = [
    {
        id : 1,
        type : 'STUDENT',
        name : 'Harsh Bisht',
        email : 'harshbisht@gmail.com',
        field2 : 'CSDS',
        field3 : 'A',
        field4 : '2000321540026',
        field5 : '8',
        field6 : 'i',
    },
    {
        id : 2,
        type : 'STUDENT',
        name : 'Harsh Bisht',
        email : 'harshbisht@gmail.com',
        field2 : 'CSDS',
        field3 : 'A',
        field4 : '2000321540026',
        field5 : '8',
        field6 : 'i',
    },
    {
        id : 3,
        type : 'STUDENT',
        name : 'Harsh Bisht',
        email : 'harshbisht@gmail.com',
        field2 : 'CSDS',
        field3 : 'A',
        field4 : '2000321540026',
        field5 : '8',
        field6 : 'i',
    },
    {
        id : 4,
        type : 'STUDENT',
        name : 'Harsh Bisht',
        email : 'harshbisht@gmail.com',
        field2 : 'CSDS',
        field3 : 'A',
        field4 : '2000321540026',
        field5 : '8',
        field6 : 'i',
    },
]